### ISSUE TITLE
Fix AOP example in sat-core

### ISSUE THREAD

**Issue by arnosthavelka** [arnosthavelka/spring-advanced-training#2]
Mainly `DrinkEnhancer` -> it's failing after the upgrade to SB 2.4 on:
```
Caused by: org.aspectj.weaver.reflect.ReflectionWorld$ReflectionWorldException: warning can't determine implemented interfaces of missing type org.springframework.boot.validation.beanvalidation.MethodValidationExcludeFilter$$Lambda$833.0x0000000800f2ec20
 [Xlint:cantFindType]
	at org.aspectj.weaver.reflect.ReflectionWorld$ExceptionBasedMessageHandler.handleMessage(ReflectionWorld.java:219)
	at org.aspectj.weaver.Lint$Kind.signal(Lint.java:340)
	at org.aspectj.weaver.MissingResolvedTypeWithKnownSignature.raiseCantFindType(MissingResolvedTypeWithKnownSignature.java:237)
	at org.aspectj.weaver.MissingResolvedTypeWithKnownSignature.getDeclaredInterfaces(MissingResolvedTypeWithKnownSignature.java:86)
	at org.aspectj.weaver.ResolvedType.getDirectSupertypes(ResolvedType.java:85)
	at org.aspectj.weaver.patterns.TypePattern.matchesSubtypes(TypePattern.java:178)
	at org.aspectj.weaver.patterns.TypePattern.matchesStatically(TypePattern.java:130)
	at org.aspectj.weaver.internal.tools.TypePatternMatcherImpl.matches(TypePatternMatcherImpl.java:31)
	at org.springframework.aop.aspectj.TypePatternClassFilter.matches(TypePatternClassFilter.java:104)
	at org.springframework.aop.support.ClassFilters$IntersectionClassFilter.matches(ClassFilters.java:145)
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:285)
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:270)
	at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:311)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:128)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:97)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:78)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:337)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:289)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:444)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
	... 84 common frames omitted
```

Add also aspect for annotation -> see https://www.baeldung.com/spring-aop-annotation

See:
- https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop
- https://www.knowledgewalls.com/j2ee/books/spring-30-examples/how-to-use-declareparents-annotation-in-spring-framework-with-example
- https://stackoverflow.com/questions/55161024/cant-determine-implemented-interfaces-of-missing-type
- https://www.nuomiphp.com/eplan/en/39800.html

**Comment by arnosthavelka** [comment]
https://stackoverflow.com/questions/6567106/anyone-have-a-spring-aop-declareparents-example

**Comment by arnosthavelka** [comment]
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop

**Comment by arnosthavelka** [comment]
Fixed by switching `AopApplication` to:
```
@Configuration
@EnableAspectJAutoProxy
public class AopConfig {
  ...
}
```
