### ISSUE TITLE
Fix bean loading by the package name

### ISSUE THREAD

**Issue by arnosthavelka** [arnosthavelka/spring-advanced-training#3]
The configuration in `com.github.aha.sat.core.testing.profile.PackageConfig` class is not working as:
```
@Configuration
@ComponentScan(basePackageClasses = { Calc.class })
public class PackageConfig {
```
It leads to this error in `RepeatAnnotationTest` and `TimedAnnotationTest` tests:
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.aha.sat.core.config.User' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1777)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 88 common frames omitted
```

**Comment by arnosthavelka** [comment]
fixed
